blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.index, name='index'),
    path('post/list/', views.post_list, name='post_list'),
    path('post/list/<str:category>/', views.post_list, name='post_list_category'),
    path('post/detail/<int:post_id>/', views.post_detail, name='post_detail'),
    path('post/comment/<int:post_id>/', views.post_comment, name='post_comment'),
    path('search/', views.post_search, name='post_search'),
    path('ticket/', views.ticket, name='ticket'),
    path('profile/', views.profile, name='profile'),
    path('profile/post/create/', views.post_create, name='post_create'),
    path('profile/post/delete/<int:post_id>/', views.post_delete, name='post_delete'),
    path('profile/post/update/<int:post_id>/', views.post_update, name='post_update'),
    path('profile/image/delete/<int:image_id>/', views.image_delete, name='image_delete'),
    path('register/', views.user_register, name='register'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('edit/account/', views.edit_account, name='edit_account'),
    path('password_change/', views.CustomPasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', views.CustomPasswordChangeDoneView.as_view(), name='password_change_done'),
    path('reset_password/', views.CustomPasswordResetView.as_view(), name='password_reset'),
    path('reset_password/done/', views.CustomPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset_password/confirm/<uidb64>/<token>/', views.CustomPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset_password/complete/', views.CustomPasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

weblog_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _

urlpatterns = []
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blog')),
    path('rosetta/', include('rosetta.urls')),
)
admin.sites.AdminSite.site_title = _('پنل مدیریت')
admin.sites.AdminSite.site_header = _('پنل مدیریت')
admin.sites.AdminSite.index_title = _('پنل مدیریت')

blog/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from .models import *


class TicketForm(forms.Form):
    SUBJECT_CHOICES = (
        ('پیشنهاد', _('پیشنهاد')),
        ('انتقاد', _('انتقاد')),
        ('گزارش', _('گزارش')),
    )
    name = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control'}), label=_('نام'))
    description = forms.CharField(max_length=500, widget=forms.Textarea(attrs={'class': 'form-control', 'rows': '5'}),
                                  label=_('توضیحات'))
    email = forms.EmailField(max_length=100, widget=forms.EmailInput(attrs={'class': 'form-control'}), label=_('ایمیل'))
    phone_number = forms.CharField(max_length=11, widget=forms.TextInput(attrs={'class': 'form-control'}),
                                   label=_('شماره تلفن'))
    subject = forms.ChoiceField(choices=SUBJECT_CHOICES, widget=forms.Select(attrs={'class': 'form-control'}),
                                label=_('موضوع'))

    def clean_phone_number(self):
        phone_number = self.cleaned_data.get('phone_number')
        if phone_number:
            if not phone_number.isnumeric():
                raise forms.ValidationError(_('شماره تلفن عددی نیست'))
            else:
                return phone_number


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'description']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control', 'rows': '5'}),
        }

    def clean_name(self):
        name = self.cleaned_data.get('name')
        if name:
            if len(name) > 100:
                raise forms.ValidationError('نام بیشتر از 100 کاراکتر نباید باشد')
            else:
                return name

    def clean_description(self):
        description = self.cleaned_data.get('description')
        if description:
            if len(description) > 500:
                raise forms.ValidationError('نام بیشتر از 500 کاراکتر نباید باشد')
            else:
                return description


class SearchForm(forms.Form):
    query = forms.CharField()


class PostCreateForm(forms.ModelForm):
    image1 = forms.ImageField(label=_('تصویر اول'), widget=forms.FileInput(attrs={'class': 'form-control'}))
    image2 = forms.ImageField(label=_('تصویر دوم'), widget=forms.FileInput(attrs={'class': 'form-control'}))

    class Meta:
        model = Post
        fields = ['title', 'description', 'reading_time', 'category']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control', 'id': "con-name"}),
            'description': forms.Textarea(attrs={'class': 'form-control', 'rows': '5'}),
            'reading_time': forms.NumberInput(attrs={'class': 'form-control'}),
            'category': forms.Select(attrs={'class': 'form-select'}),
        }


class PostUpdateForm(forms.ModelForm):
    image1 = forms.ImageField(label=_('تصویر اول'), widget=forms.FileInput(attrs={'class': 'form-control'}))
    image2 = forms.ImageField(label=_('تصویر دوم'), widget=forms.FileInput(attrs={'class': 'form-control'}))

    class Meta:
        model = Post
        fields = ['title', 'description', 'reading_time', 'category']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control', 'id': "con-name"}),
            'description': forms.Textarea(attrs={'class': 'form-control', 'rows': '5'}),
            'reading_time': forms.NumberInput(attrs={'class': 'form-control'}),
            'category': forms.Select(attrs={'class': 'form-select'}),
        }


class RegisterForm(forms.ModelForm):
    password1 = forms.CharField(max_length=200, widget=forms.PasswordInput(attrs={'class': 'form-control'}),
                                label=_('پسورد'))
    password2 = forms.CharField(max_length=200, widget=forms.PasswordInput(attrs={'class': 'form-control'}),
                                label=_('تکرار پسورد'))

    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name']
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
        }

    def clean(self):
        cd = super().clean()
        password1 = cd.get('password1')
        password2 = cd.get('password2')
        if password1 and password2 and password1 != password2:
            raise ValidationError('پسورد ها باید مطابقت داشته باشند')


class LoginForm(forms.Form):
    username = forms.CharField(max_length=200, required=True, widget=forms.TextInput(attrs={'class': 'form-control'}),
                               label=_('نام کاربری'))
    password = forms.CharField(max_length=200, required=True,
                               widget=forms.PasswordInput(attrs={'class': 'form-control'}), label=_('پسورد'))


class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
        }


class AccountEditForm(forms.ModelForm):
    class Meta:
        model = Account
        fields = ['date_of_birth', 'bio', 'job', 'photo']
        widgets = {
            'date_of_birth': forms.DateInput(attrs={'class': 'form-control'}),
            'bio': forms.Textarea(attrs={'class': 'form-control', 'rows': '5'}),
            'job': forms.TextInput(attrs={'class': 'form-control'}),
            'photo': forms.FileInput(attrs={'class': 'form-control'}),
        }

blog/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import (PasswordChangeView, PasswordChangeDoneView, PasswordResetView,
                                       PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView)
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views.decorators.http import require_POST
from .forms import *


def index(request):
    return render(request, 'blog/index.html')


def post_list(request, category=None):
    if category is not None:
        posts = Post.published.filter(category=category)
    else:
        posts = Post.published.all()
    paginator = Paginator(posts, 2)
    page_number = request.GET.get('page', 1)
    try:
        posts = paginator.page(page_number)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    except PageNotAnInteger:
        posts = paginator.page(1)
    context = {
        'posts': posts,
        'category': category,
    }
    return render(request, 'blog/post_list.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
    form = CommentForm()
    comments = post.comments.filter(active=True)
    content = {
        'post': post,
        'form': form,
        'comments': comments,
    }
    return render(request, 'blog/post_detail.html', content)


@login_required
@require_POST
def post_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
    comment = None
    form = CommentForm(request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.post = post
        comment.save()
    context = {'post': post, 'comment': comment, 'form': form}
    return render(request, 'forms/comment.html', context)


def post_search(request):
    query = None
    results = []
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            results = Post.published.filter(Q(title__icontains=query) | Q(description__icontains=query))
    context = {'query': query, 'results': results}
    return render(request, 'blog/search.html', context)


def ticket(request):
    if request.method == 'POST':
        form = TicketForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            Ticket.objects.create(name=cd['name'], description=cd['description'], email=cd['email'],
                                  phone_number=cd['phone_number'], subject=cd['subject'])
            return redirect('blog:index')
    else:
        form = TicketForm()
    return render(request, 'forms/ticket.html', {'form': form})


@login_required
def profile(request):
    posts = Post.published.filter(author=request.user)
    return render(request, 'blog/profile.html', {'posts': posts})


@login_required
def post_create(request):
    if request.method == 'POST':
        form = PostCreateForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            Image.objects.create(image_file=form.cleaned_data.get('image1'), post=post)
            Image.objects.create(image_file=form.cleaned_data.get('image2'), post=post)
            return redirect('blog:profile')
    else:
        form = PostCreateForm()
    return render(request, 'forms/post_create.html', {'form': form})


@login_required
def post_delete(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if request.method == 'POST':
        post.delete()
        return redirect('blog:profile')
    return render(request, 'forms/post_delete.html', {'post': post})


@login_required
def post_update(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if request.method == 'POST':
        form = PostUpdateForm(data=request.POST, files=request.FILES, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            Image.objects.create(image_file=form.cleaned_data.get('image1'), post=post)
            Image.objects.create(image_file=form.cleaned_data.get('image2'), post=post)
            return redirect('blog:profile')
    else:
        form = PostUpdateForm(instance=post)
    context = {'form': form, 'post': post}
    return render(request, 'forms/post_update.html', context)


@login_required
def image_delete(request, image_id):
    image = get_object_or_404(Image, id=image_id)
    if request.method == 'POST':
        image.delete()
        return redirect('blog:profile')
    return render(request, 'forms/image_delete.html', {'image': image})


def user_register(request):
    if request.user.is_authenticated:
        return redirect('blog:index')
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data.get('password1'))
            user.save()
            Account.objects.create(user=user)
            return render(request, 'registration/register_done.html', {'user': user})
    else:
        form = RegisterForm()
    return render(request, 'registration/register.html', {'form': form})


def user_login(request):
    if request.user.is_authenticated:
        return redirect('blog:index')
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(request, username=cd['username'], password=cd['password'])
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('blog:profile')
                else:
                    return HttpResponse('this account is disabled')
            else:
                return HttpResponse('you are not logged in')
    else:
        form = LoginForm()
    return render(request, 'registration/login.html', {'form': form})


@login_required
def user_logout(request):
    if request.method == 'POST':
        logout(request)
        return redirect('blog:index')
    return render(request, 'registration/logged_out.html')


@login_required
def edit_account(request):
    if request.method == 'POST':
        user_form = UserEditForm(data=request.POST, instance=request.user)
        account_form = AccountEditForm(data=request.POST, files=request.FILES, instance=request.user.account)
        if user_form.is_valid() and account_form.is_valid():
            user_form.save()
            account_form.save()
            return redirect('blog:profile')
    else:
        user_form = UserEditForm(instance=request.user)
        account_form = AccountEditForm(instance=request.user.account)
    context = {'user_form': user_form, 'account_form': account_form}
    return render(request, 'registration/edit_account.html', context)


class CustomPasswordChangeView(PasswordChangeView):
    template_name = 'registration/password_change_form.html'
    success_url = reverse_lazy('blog:password_change_done')


class CustomPasswordChangeDoneView(PasswordChangeDoneView):
    template_name = 'registration/password_change_done.html'


class CustomPasswordResetView(PasswordResetView):
    template_name = 'registration/password_reset_form.html'
    email_template_name = 'registration/password_reset_email.html'
    success_url = reverse_lazy('blog:password_reset_done')


class CustomPasswordResetDoneView(PasswordResetDoneView):
    template_name = 'registration/password_reset_done.html'


class CustomPasswordResetConfirmView(PasswordResetConfirmView):
    template_name = 'registration/password_reset_confirm.html'
    success_url = reverse_lazy('blog:password_reset_complete')


class CustomPasswordResetCompleteView(PasswordResetCompleteView):
    template_name = 'registration/password_reset_complete.html'

blog/templates/partials/footer.html
{% load i18n %}
{% load static %}
<footer class="pb-0">
    <div class="container">
        <hr>
        <!-- Widgets START -->
        <div class="row pt-5">
            <!-- Footer Widget -->
            <div class="col-md-6 col-lg-4 mb-4">
                <h5 class="mb-4">{% trans 'لینک های مفید' %}</h5>
                <div class="row">
                    <div class="col-6">
                        <ul class="nav flex-column">
                            <li class="nav-item"><a class="nav-link pt-0" href="{% url 'blog:post_list' %}">{% trans 'لیست پست ها' %}</a></li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'blog:profile' %}">{% trans 'داشبورد' %}</a></li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'blog:ticket' %}">{% trans 'ارسال تیکت' %}</a></li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'blog:post_create' %}">{% trans 'ایجاد پست' %}</a>
                            </li>
                        </ul>
                    </div>
                    <div class="col-6">
                        <ul class="nav flex-column">
                            <li class="nav-item">
                                <a class="nav-link pt-0" href="{% url 'blog:post_list_category' 'برنامه-نویسی-وب' %}">{% trans 'برنامه نویسی وبسایت' %}</a></li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'blog:post_list_category' 'طراحی-وبسایت' %}">{% trans 'طراحی وبسایت' %}</a></li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'blog:post_list_category' 'برنامه-نویسی-موبایل' %}">{% trans 'برنامه نویسی موبایل' %}</a></li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'blog:post_list_category' 'هوش-مصنوعی' %}">{% trans 'هوش مصنوعی' %}</a></li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'blog:post_list_category' 'سایر' %}">{% trans 'سایر' %}</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>

            <!-- Footer Widget -->
            <div class="col-sm-6 col-lg-4 mb-4">
                <h5 class="mb-4">{% trans 'پربیننده ترین' %}</h5>
                <ul class="list-inline">
                    <li class="list-inline-item">
                        <a href="{% url 'blog:post_list_category' 'برنامه-نویسی-وب' %}" class="btn btn-sm btn-primary-soft">{% trans 'برنامه نویسی وبسایت' %}</a></li>
                    <li class="list-inline-item">
                        <a href="{% url 'blog:post_list_category' 'طراحی-وبسایت' %}" class="btn btn-sm btn-success-soft">{% trans 'طراحی وبسایت' %}</a></li>
                    <li class="list-inline-item">
                        <a href="{% url 'blog:post_list_category' 'برنامه-نویسی-موبایل' %}" class="btn btn-sm btn-warning-soft">{% trans 'برنامه نویسی موبایل' %}</a> </li>
                    <li class="list-inline-item">
                        <a href="{% url 'blog:post_list_category' 'هوش-مصنوعی' %}" class="btn btn-sm btn-danger-soft">{% trans 'هوش مصنوعی' %}</a></li>
                    <li class="list-inline-item">
                        <a href="{% url 'blog:post_list_category' 'سایر' %}" class="btn btn-sm btn-info-soft">{% trans 'سایر' %}</a></li>
                </ul>
            </div>

            <!-- Footer Widget -->
            <div class="col-sm-6 col-lg-4 mb-4">
                <h5 class="mb-4">{% trans 'شبکه های اجتماعی' %}</h5>
                <ul class="nav flex-column">
                    <li class="nav-item"><a class="nav-link pt-0" href="#"><i
                            class="fab fa-facebook-square fa-fw me-2 text-facebook"></i>{% trans 'فیسبوک' %}</a></li>
                    <li class="nav-item"><a class="nav-link" href="#"><i
                            class="fab fa-twitter-square fa-fw me-2 text-twitter"></i>{% trans 'تویتر' %}</a></li>
                    <li class="nav-item"><a class="nav-link" href="#"><i
                            class="fab fa-linkedin fa-fw me-2 text-linkedin"></i>{% trans 'لینکدین' %}</a></li>
                    <li class="nav-item"><a class="nav-link" href="#"><i
                            class="fab fa-youtube-square fa-fw me-2 text-youtube"></i>{% trans 'یوتیوب' %}</a></li>
                </ul>
            </div>
        </div>
        <!-- Widgets END -->
    </div>
</footer>

blog/templates/partials/footer_references.html
<script>
		const storedTheme = localStorage.getItem('theme')

		const getPreferredTheme = () => {
			if (storedTheme) {
				return storedTheme
			}
			return window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light'
		}

		const setTheme = function (theme) {
			if (theme === 'auto' && window.matchMedia('(prefers-color-scheme: dark)').matches) {
				document.documentElement.setAttribute('data-bs-theme', 'dark')
			} else {
				document.documentElement.setAttribute('data-bs-theme', theme)
			}
		}

		setTheme(getPreferredTheme())

		window.addEventListener('DOMContentLoaded', () => {
		    var el = document.querySelector('.theme-icon-active');
			if(el != 'undefined' && el != null) {
				const showActiveTheme = theme => {
				const activeThemeIcon = document.querySelector('.theme-icon-active use')
				const btnToActive = document.querySelector(`[data-bs-theme-value="${theme}"]`)
				const svgOfActiveBtn = btnToActive.querySelector('.mode-switch use').getAttribute('href')

				document.querySelectorAll('[data-bs-theme-value]').forEach(element => {
					element.classList.remove('active')
				})

				btnToActive.classList.add('active')
				activeThemeIcon.setAttribute('href', svgOfActiveBtn)
			}

			window.matchMedia('(prefers-color-scheme: dark)').addEventListener('change', () => {
				if (storedTheme !== 'light' || storedTheme !== 'dark') {
					setTheme(getPreferredTheme())
				}
			})

			showActiveTheme(getPreferredTheme())

			document.querySelectorAll('[data-bs-theme-value]')
				.forEach(toggle => {
					toggle.addEventListener('click', () => {
						const theme = toggle.getAttribute('data-bs-theme-value')
						localStorage.setItem('theme', theme)
						setTheme(theme)
						showActiveTheme(theme)
					})
				})

			}
		})

	</script>

blog/templates/partials/header_references.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'vendor/font-awesome/css/all.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'vendor/bootstrap-icons/bootstrap-icons.css' %}">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link rel="stylesheet" type="text/css" href="{% static 'vendor/glightbox/css/glightbox.css' %}">
<link rel="shortcut icon" href="{% static 'images/icon/blog-logo.png' %}">

blog/templates/partials/latest_posts.html
{% load static %}
{% load blog_tags %}
{% load jformat %}

{% for post in l_posts %}
    <div class="col-sm-6 col-lg-4">
        <!-- Card item START -->
        <div class="card">
            <!-- Card img -->
            <div class="position-relative">
                <img class="card-img rounded-0" src="{{ post.images.first.image_file.url }}" alt="Card image">
                <div class="card-img-overlay d-flex align-items-start flex-column p-3">
                    <!-- Card overlay bottom -->
                    <div class="w-100 mt-auto">
                        <a href="#" class="badge text-bg-dark mb-2">{{ post.category }}</a>
                    </div>
                </div>
            </div>
            <div class="card-body px-0 pt-3">
                <h4 class="card-title"><a href="{{ post.get_absolute_url }}"
                                          class="btn-link text-reset stretched-link">{{ post.title }}</a></h4>
                <!-- Card info -->
                <p>{{ post.description | markdown | truncatewords:50 }}</p>
                <!-- Card info -->
                <ul class="nav nav-divider align-items-center">
                    <li class="nav-item">{{ post.publish|jformat:"%Y/%m/%d-%H:%M" }}</li>
                </ul>
            </div>
        </div>
    </div>
{% endfor %}

blog/templates/partials/pagination.html
{% load i18n %}
{% if posts %}
    <nav class="my-5" aria-label="navigation">
        <ul class="pagination d-inline-block d-md-flex justify-content-center">
            {% if page.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page.previous_page_number }}" tabindex="-1"
                       aria-disabled="true">{% trans 'قبل' %}</a>
                </li>
                {% if page.number > 3 %}
                    <li class="page-item"><a class="page-link" href="?page=1">1</a></li>
                    {% if page.number > 4 %}
                        <li class="page-item disabled"><a class="page-link" href="#">...</a></li>
                    {% endif %}
                {% endif %}
            {% endif %}

            {% for num in page.paginator.page_range %}
                {% if page.number == num %}
                    <li class="page-item"><a class="page-link active" href="?page={{ num }}">{{ num }}</a></li>
                {% elif num > page.number|add:'-3' and num < page.number|add:'3' %}
                    <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
                {% endif %}
            {% endfor %}

            {% if page.has_next %}
                {% if page.number < page.paginator.num_pages|add:'-3' %}
                    <li class="page-item disabled"><a class="page-link" href="#">...</a></li>
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page.paginator.num_pages }}">
                            {{ page.paginator.num_pages }}
                        </a>
                    </li>
                {% elif page.number < page.paginator.num_pages|add:'-2' %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page.paginator.num_pages }}">
                            {{ page.paginator.num_pages }}
                        </a>
                    </li>
                {% endif %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page.next_page_number }}">{% trans 'بعد' %}</a>
                </li>
            {% endif %}
        </ul>
    </nav>
{% endif %}