blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.index, name='index'),
    path('post/list/', views.post_list, name='post_list'),
    path('post/list/<str:category>/', views.post_list, name='post_list_category'),
    path('post/detail/<int:post_id>/', views.post_detail, name='post_detail'),
    path('post/comment/<int:post_id>/', views.post_comment, name='post_comment'),
    path('search/', views.post_search, name='post_search'),
    path('ticket/', views.ticket, name='ticket'),
    path('profile/', views.profile, name='profile'),
    path('profile/post/create/', views.post_create, name='post_create'),
    path('profile/post/delete/<int:post_id>/', views.post_delete, name='post_delete'),
    path('profile/post/update/<int:post_id>/', views.post_update, name='post_update'),
    path('profile/image/delete/<int:image_id>/', views.image_delete, name='image_delete'),
    path('register/', views.user_register, name='register'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('edit/account/', views.edit_account, name='edit_account'),
    path('password_change/', views.CustomPasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', views.CustomPasswordChangeDoneView.as_view(), name='password_change_done'),
    path('reset_password/', views.CustomPasswordResetView.as_view(), name='password_reset'),
    path('reset_password/done/', views.CustomPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset_password/confirm/<uidb64>/<token>/', views.CustomPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset_password/complete/', views.CustomPasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

weblog_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _

urlpatterns = []
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blog')),
    path('rosetta/', include('rosetta.urls')),
)
admin.sites.AdminSite.site_title = _('پنل مدیریت')
admin.sites.AdminSite.site_header = _('پنل مدیریت')
admin.sites.AdminSite.index_title = _('پنل مدیریت')

blog/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from .models import *


class TicketForm(forms.Form):
    SUBJECT_CHOICES = (
        ('پیشنهاد', _('پیشنهاد')),
        ('انتقاد', _('انتقاد')),
        ('گزارش', _('گزارش')),
    )
    name = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control'}), label=_('نام'))
    description = forms.CharField(max_length=500, widget=forms.Textarea(attrs={'class': 'form-control', 'rows': '5'}),
                                  label=_('توضیحات'))
    email = forms.EmailField(max_length=100, widget=forms.EmailInput(attrs={'class': 'form-control'}), label=_('ایمیل'))
    phone_number = forms.CharField(max_length=11, widget=forms.TextInput(attrs={'class': 'form-control'}),
                                   label=_('شماره تلفن'))
    subject = forms.ChoiceField(choices=SUBJECT_CHOICES, widget=forms.Select(attrs={'class': 'form-control'}),
                                label=_('موضوع'))

    def clean_phone_number(self):
        phone_number = self.cleaned_data.get('phone_number')
        if phone_number:
            if not phone_number.isnumeric():
                raise forms.ValidationError(_('شماره تلفن عددی نیست'))
            else:
                return phone_number


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'description']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control', 'rows': '5'}),
        }

    def clean_name(self):
        name = self.cleaned_data.get('name')
        if name:
            if len(name) > 100:
                raise forms.ValidationError('نام بیشتر از 100 کاراکتر نباید باشد')
            else:
                return name

    def clean_description(self):
        description = self.cleaned_data.get('description')
        if description:
            if len(description) > 500:
                raise forms.ValidationError('نام بیشتر از 500 کاراکتر نباید باشد')
            else:
                return description


class SearchForm(forms.Form):
    query = forms.CharField()


class PostCreateForm(forms.ModelForm):
    image1 = forms.ImageField(label=_('تصویر اول'), widget=forms.FileInput(attrs={'class': 'form-control'}))
    image2 = forms.ImageField(label=_('تصویر دوم'), widget=forms.FileInput(attrs={'class': 'form-control'}))

    class Meta:
        model = Post
        fields = ['title', 'description', 'reading_time', 'category']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control', 'id': "con-name"}),
            'description': forms.Textarea(attrs={'class': 'form-control', 'rows': '5'}),
            'reading_time': forms.NumberInput(attrs={'class': 'form-control'}),
            'category': forms.Select(attrs={'class': 'form-select'}),
        }


class PostUpdateForm(forms.ModelForm):
    image1 = forms.ImageField(label=_('تصویر اول'), widget=forms.FileInput(attrs={'class': 'form-control'}))
    image2 = forms.ImageField(label=_('تصویر دوم'), widget=forms.FileInput(attrs={'class': 'form-control'}))

    class Meta:
        model = Post
        fields = ['title', 'description', 'reading_time', 'category']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control', 'id': "con-name"}),
            'description': forms.Textarea(attrs={'class': 'form-control', 'rows': '5'}),
            'reading_time': forms.NumberInput(attrs={'class': 'form-control'}),
            'category': forms.Select(attrs={'class': 'form-select'}),
        }


class RegisterForm(forms.ModelForm):
    password1 = forms.CharField(max_length=200, widget=forms.PasswordInput(attrs={'class': 'form-control'}),
                                label=_('پسورد'))
    password2 = forms.CharField(max_length=200, widget=forms.PasswordInput(attrs={'class': 'form-control'}),
                                label=_('تکرار پسورد'))

    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name']
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
        }

    def clean(self):
        cd = super().clean()
        password1 = cd.get('password1')
        password2 = cd.get('password2')
        if password1 and password2 and password1 != password2:
            raise ValidationError('پسورد ها باید مطابقت داشته باشند')


class LoginForm(forms.Form):
    username = forms.CharField(max_length=200, required=True, widget=forms.TextInput(attrs={'class': 'form-control'}),
                               label=_('نام کاربری'))
    password = forms.CharField(max_length=200, required=True,
                               widget=forms.PasswordInput(attrs={'class': 'form-control'}), label=_('پسورد'))


class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
        }


class AccountEditForm(forms.ModelForm):
    class Meta:
        model = Account
        fields = ['date_of_birth', 'bio', 'job', 'photo']
        widgets = {
            'date_of_birth': forms.DateInput(attrs={'class': 'form-control'}),
            'bio': forms.Textarea(attrs={'class': 'form-control', 'rows': '5'}),
            'job': forms.TextInput(attrs={'class': 'form-control'}),
            'photo': forms.FileInput(attrs={'class': 'form-control'}),
        }

blog/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import (PasswordChangeView, PasswordChangeDoneView, PasswordResetView,
                                       PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView)
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views.decorators.http import require_POST
from .forms import *


def index(request):
    return render(request, 'blog/index.html')


def post_list(request, category=None):
    if category is not None:
        posts = Post.published.filter(category=category)
    else:
        posts = Post.published.all()
    paginator = Paginator(posts, 2)
    page_number = request.GET.get('page', 1)
    try:
        posts = paginator.page(page_number)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    except PageNotAnInteger:
        posts = paginator.page(1)
    context = {
        'posts': posts,
        'category': category,
    }
    return render(request, 'blog/post_list.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
    form = CommentForm()
    comments = post.comments.filter(active=True)
    content = {
        'post': post,
        'form': form,
        'comments': comments,
    }
    return render(request, 'blog/post_detail.html', content)


@login_required
@require_POST
def post_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
    comment = None
    form = CommentForm(request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.post = post
        comment.save()
    context = {'post': post, 'comment': comment, 'form': form}
    return render(request, 'forms/comment.html', context)


def post_search(request):
    query = None
    results = []
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            results = Post.published.filter(Q(title__icontains=query) | Q(description__icontains=query))
    context = {'query': query, 'results': results}
    return render(request, 'blog/search.html', context)


def ticket(request):
    if request.method == 'POST':
        form = TicketForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            Ticket.objects.create(name=cd['name'], description=cd['description'], email=cd['email'],
                                  phone_number=cd['phone_number'], subject=cd['subject'])
            return redirect('blog:index')
    else:
        form = TicketForm()
    return render(request, 'forms/ticket.html', {'form': form})


@login_required
def profile(request):
    posts = Post.published.filter(author=request.user)
    return render(request, 'blog/profile.html', {'posts': posts})


@login_required
def post_create(request):
    if request.method == 'POST':
        form = PostCreateForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            Image.objects.create(image_file=form.cleaned_data.get('image1'), post=post)
            Image.objects.create(image_file=form.cleaned_data.get('image2'), post=post)
            return redirect('blog:profile')
    else:
        form = PostCreateForm()
    return render(request, 'forms/post_create.html', {'form': form})


@login_required
def post_delete(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if request.method == 'POST':
        post.delete()
        return redirect('blog:profile')
    return render(request, 'forms/post_delete.html', {'post': post})


@login_required
def post_update(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if request.method == 'POST':
        form = PostUpdateForm(data=request.POST, files=request.FILES, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            Image.objects.create(image_file=form.cleaned_data.get('image1'), post=post)
            Image.objects.create(image_file=form.cleaned_data.get('image2'), post=post)
            return redirect('blog:profile')
    else:
        form = PostUpdateForm(instance=post)
    context = {'form': form, 'post': post}
    return render(request, 'forms/post_update.html', context)


@login_required
def image_delete(request, image_id):
    image = get_object_or_404(Image, id=image_id)
    if request.method == 'POST':
        image.delete()
        return redirect('blog:profile')
    return render(request, 'forms/image_delete.html', {'image': image})


def user_register(request):
    if request.user.is_authenticated:
        return redirect('blog:index')
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data.get('password1'))
            user.save()
            Account.objects.create(user=user)
            return render(request, 'registration/register_done.html', {'user': user})
    else:
        form = RegisterForm()
    return render(request, 'registration/register.html', {'form': form})


def user_login(request):
    if request.user.is_authenticated:
        return redirect('blog:index')
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(request, username=cd['username'], password=cd['password'])
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('blog:profile')
                else:
                    return HttpResponse('this account is disabled')
            else:
                return HttpResponse('you are not logged in')
    else:
        form = LoginForm()
    return render(request, 'registration/login.html', {'form': form})


@login_required
def user_logout(request):
    if request.method == 'POST':
        logout(request)
        return redirect('blog:index')
    return render(request, 'registration/logged_out.html')


@login_required
def edit_account(request):
    if request.method == 'POST':
        user_form = UserEditForm(data=request.POST, instance=request.user)
        account_form = AccountEditForm(data=request.POST, files=request.FILES, instance=request.user.account)
        if user_form.is_valid() and account_form.is_valid():
            user_form.save()
            account_form.save()
            return redirect('blog:profile')
    else:
        user_form = UserEditForm(instance=request.user)
        account_form = AccountEditForm(instance=request.user.account)
    context = {'user_form': user_form, 'account_form': account_form}
    return render(request, 'registration/edit_account.html', context)


class CustomPasswordChangeView(PasswordChangeView):
    template_name = 'registration/password_change_form.html'
    success_url = reverse_lazy('blog:password_change_done')


class CustomPasswordChangeDoneView(PasswordChangeDoneView):
    template_name = 'registration/password_change_done.html'


class CustomPasswordResetView(PasswordResetView):
    template_name = 'registration/password_reset_form.html'
    email_template_name = 'registration/password_reset_email.html'
    success_url = reverse_lazy('blog:password_reset_done')


class CustomPasswordResetDoneView(PasswordResetDoneView):
    template_name = 'registration/password_reset_done.html'


class CustomPasswordResetConfirmView(PasswordResetConfirmView):
    template_name = 'registration/password_reset_confirm.html'
    success_url = reverse_lazy('blog:password_reset_complete')


class CustomPasswordResetCompleteView(PasswordResetCompleteView):
    template_name = 'registration/password_reset_complete.html'

blog/templates/forms/comment.html
{% extends 'parent/base.html' %}
{% load jformat %}
{% load static %}
{% load i18n %}
{% block title %}post comment{% endblock %}

{% block content %}
    {% if comment %}
        <div class="centered mb-4 text-center">
            <h2 class="h1 m-0">{% trans 'کامنت شما ثبت شد' %}</h2>
            <br>
            <a href="{{ post.get_absolute_url }}" class="btn btn-dark mb-0">{% trans 'بازگشت به پست' %}</a>
        </div>
    {% else %}
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="{% trans 'افزودن کامنت' %}">
        </form>
    {% endif %}
    <!-- Bootstrap JS -->
    <script src="{% static 'vendor/bootstrap/dist/js/bootstrap.bundle.min.js' %}"></script>
    <!-- Template Functions -->
    <script src="{% static 'js/functions.js' %}"></script>
{% endblock %}

blog/templates/forms/image_delete.html
{% extends 'parent/base.html' %}
{% load i18n %}
{% load jformat %}
{% block title %}image delete{% endblock %}

{% block content %}
    <div class="centered mb-4 text-center">
        <h2 class="h1 m-0"> {% trans 'آیا از حذف تصویر مطمعن هستید؟' %} </h2>
        <br>
        <a href="{% url 'blog:profile' %}" class="btn btn-dark mb-0">{% trans 'برگشت به صفحه پروفایل' %}</a>
    </div>
    <br>
    <form method="post">
        {% csrf_token %}
        <div class="centered mb-4 text-center">
            <button class="btn btn-primary center" type="submit">{% trans 'حذف' %}</button>
        </div>
    </form>
{% endblock %}

blog/templates/forms/post_create.html
{% extends 'parent/base.html' %}
{% load i18n %}
{% load static %}
{% block title %}post create{% endblock %}
{% block content %}
    <section class="py-4">
        <div class="container">
            <div class="row pb-4">
                <div class="col-12">
                    <!-- Title -->
                    <h1 class="mb-0 h3">{% trans 'ایجاد پست' %}</h1>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <!-- Chart START -->
                    <div class="card border h-100">
                        <!-- Card body -->
                        <div class="card-body">
                            <!-- Form START -->
                            <form method="post" enctype="multipart/form-data">
                                <div class="row">
                                    <div class="col-12">
                                        {% csrf_token %}
                                        {{ form.as_p }}
                                    </div>
                                </div>
                                <button class="btn btn-primary" type="submit">{% trans 'ایجاد پست' %}</button>
                            </form>
                        </div>
                        <!-- Form END -->
                    </div>
                </div><!-- Chart END -->
            </div>
        </div>
    </section>
    <script src="{% static 'vendor/bootstrap/dist/js/bootstrap.bundle.min.js' %}"></script>
    <!-- Vendors -->
    <script src="{% static 'vendor/apexcharts/js/apexcharts.min.js' %}"></script>
    <script src="{% static 'vendor/quill/js/quill.min.js' %}"></script>
    <!-- Template Functions -->
    <script src="{% static 'js/functions.js' %}"></script>
    <!-- Btn Upload -->
    <script>
        document.querySelector(".upload-button").addEventListener("click", () => {
            //clicks on the file input
            document.querySelector(".hidden-upload").click();
        });
        //adds event listener on the hidden file input to listen for any changes
        document.querySelector(".hidden-upload").addEventListener("change", (event) => {
            //gets the file name
            document.querySelector(".upload-name").value = event.target.files[0].name;
        });
    </script>
{% endblock %}

blog/templates/forms/post_delete.html
{% extends 'parent/base.html' %}
{% load jformat %}
{% load i18n %}
{% block title %}post delete{% endblock %}

{% block content %}
    <div class="centered mb-4 text-center">
        <h2 class="h1 m-0"> {% trans 'آیا از حذف پست مطمعن هستید؟' %}</h2>
        <br>
        <a href="{% url 'blog:profile' %}" class="btn btn-dark mb-0">{% trans 'برگشت به صفحه پروفایل' %}</a>
    </div>
    <br>
    <form method="post">
        {% csrf_token %}
        <div class="centered mb-4 text-center">
            <input type="submit" class="btn btn-primary center" value="{% trans 'حذف' %}">
        </div>
    </form>
{% endblock %}

blog/templates/forms/post_update.html
{% extends 'parent/base.html' %}
{% load i18n %}
{% load static %}
 {% block title %}post update{% endblock %}
{% block content %}
    <section class="py-4">
        <div class="container">
            <div class="row pb-4">
                <div class="col-12">
                    <!-- Title -->
                    <h1 class="mb-0 h3">{% trans 'ویرایش پست' %}</h1>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <!-- Chart START -->
                    <div class="card border h-100">
                        <!-- Card body -->
                        <div class="card-body">
                            <!-- Form START -->
                            <form method="post" enctype="multipart/form-data">
                                <div class="row">
                                    <div class="col-12">
                                        {% csrf_token %}
                                        {{ form.as_p }}
                                        {% if post %}
                                            {% for img in post.images.all %}
                                                <div class="row align-items-center mb-2">
                                                <div class="col-4 col-md-2">
                                                    <div class="position-relative">
                                                        <img class="rounded mb-3" src="{{ img.image_file.url }}" alt="">
                                                        <div class="position-absolute top-0 end-0 mt-n2 me-n2">
                                                            <a class="btn btn-icon btn-xs btn-danger"
                                                               href="{% url 'blog:image_delete' img.id %}">
                                                                <i class="bi bi-x"></i></a>
                                                        </div>
                                                    </div>
                                                </div>
                                            {% endfor %}
                                        {% endif %}
                                        </div>
                                    </div>
                                    <button class="btn btn-primary" type="submit">{% trans 'ویرایش پست' %}</button>
                                </div>
                            </form>
                            <!-- Form END -->
                        </div>
                    </div><!-- Chart END -->
                </div>
            </div>
        </div>
    </section>
    <script src="{% static 'vendor/bootstrap/dist/js/bootstrap.bundle.min.js' %}"></script>
    <!-- Vendors -->
    <script src="{% static 'vendor/apexcharts/js/apexcharts.min.js' %}"></script>
    <script src="{% static 'vendor/quill/js/quill.min.js' %}"></script>
    <!-- Template Functions -->
    <script src="{% static 'js/functions.js' %}"></script>
    <!-- Btn Upload -->
    <script>
        document.querySelector(".upload-button").addEventListener("click", () => {
            //clicks on the file input
            document.querySelector(".hidden-upload").click();
        });
        //adds event listener on the hidden file input to listen for any changes
        document.querySelector(".hidden-upload").addEventListener("change", (event) => {
            //gets the file name
            document.querySelector(".upload-name").value = event.target.files[0].name;
        });
    </script>
{% endblock %}

blog/templates/forms/ticket.html
{% extends 'parent/base.html' %}
{% load i18n %}
{% block title %}ticket form{% endblock %}
{% block content %}
    <section class="py-4">
        <div class="container">
            <div class="row pb-4">
                <div class="col-12">
                    <!-- Title -->
                    <h1 class="mb-0 h3">{% trans 'ارسال تیکت به پشتیبانی' %}</h1>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <!-- Chart START -->
                    <div class="card border h-100">
                        <!-- Card body -->
                        <div class="card-body">
                            <!-- Form START -->
                            <form method="post" novalidate>
                                {% csrf_token %}
                                <p>{{ form.non_field_errors }}</p>
                                {{ form.as_p }}
                                <br>
                                <button class="btn btn-primary" type="submit">{% trans 'ارسال تیکت' %}</button>
                            </form>
                            <!-- Form END -->
                        </div>
                    </div><!-- Chart END -->
                </div>
            </div>
        </div>
    </section>
{% endblock %}